# This workflow is designed to be run as needed to remove costly resources

name: Terraform Cleanup - Cost Savings

run-name: Terraform Cleanup - Cost Savings (${{ inputs.environments }})

on:
  workflow_dispatch:
    inputs:
      environments:
        description: Comma-separated list of environments to run against.
        required: true
        type: string
        default: dev,test,prod

      resource_targets:
        description: Comma-separated list of resources to target for destruction (optional). If omitted, all resources in the selected stack will be destroyed.
        required: false
        type: string

      stack_names:
        description: Comma-separated list of of Terraform stack names to run against.
        required: true
        type: string
        default: vpc

  # schedule:
  #   - cron: '0 0 * * *'  # This represents daily at 5 PM PST

permissions:
  contents: read
  id-token: write

env:
  # Comma-separated list of resources to target for destruction
  VPC_TARGETS: aws_eip.nat,aws_nat_gateway.nat,aws_internet_gateway.default


jobs:
  env-vars:
    name: Set Env Vars as Outputs
    runs-on: ubuntu-latest
    outputs:
      MATRIX: ${{ steps.set-outputs.outputs.matrix }}
      RESOURCE_TARGETS: ${{ steps.set-outputs.outputs.resource_targets }}
    steps:
      - name: Set Output Values
        id: set-outputs
        run: |

          ENVS="${{ github.event.inputs.environments }}"
          STACKS="${{ github.event.inputs.stack_names }}"

          # set resource targets value based on event triggering workflow
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            # for manual runs, grab list from input
            RESOURCE_TARGETS="${{ github.event.inputs.resource_targets }}"
          elif [[ "${{ github.event_name }}" == "schedule" ]]; then
            # for scheduled runs, use predefined lists
            RESOURCE_TARGETS="${VPC_TARGETS}"
          fi

          # Remove any spaces
          ENVS="${ENVS// /}"
          RESOURCE_TARGETS="${RESOURCE_TARGETS// /}"
          STACKS="${STACKS// /}"

          # Split environments and stack names into arrays
          IFS=',' read -ra ENV_ARRAY <<< "$ENVS"
          IFS=',' read -ra STACK_ARRAY <<< "$STACKS"

          MATRIX="{\"include\":["

          # Iterate through every combination of environment and stack name
          for ENV in "${ENV_ARRAY[@]}"; do
            for STACK in "${STACK_ARRAY[@]}"; do
              # Logic to match environment to account ID (adjust as needed)
              if [[ $ENV == "dev" ]]; then
                ACCOUNT_ID="${{ vars.DEV_ACCOUNT_ID }}"
              elif [[ $ENV == "test" ]]; then
                ACCOUNT_ID="${{ vars.TEST_ACCOUNT_ID }}"
              elif [[ $ENV == "prod" ]]; then
                ACCOUNT_ID="${{ vars.PROD_ACCOUNT_ID }}"
              fi
              # Construct JSON object for matrix
              MATRIX="${MATRIX}{\"environment\":[\"${ENV}\",\"${ACCOUNT_ID}\"],\"stack_name\":\"${STACK}\"},"
            done
          done
          MATRIX="${MATRIX%,}]}"

          echo "MATRIX = $MATRIX"

          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT
          echo "resource_targets=${RESOURCE_TARGETS}" >> $GITHUB_OUTPUT


  tf-destroy:
    name: Terraform Cleanup
    needs: 
      - env-vars
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.env-vars.outputs.MATRIX) }}
    uses: chrisba11/terraform-feature-stacks/.github/workflows/rw_tf_destroy.yml@main
    with:
      aws_account_id: ${{ matrix.environment[1] }}
      aws_region: ${{ vars.AWS_REGION }}
      environment: ${{ matrix.environment[0] }}
      resource_targets: ${{ needs.env-vars.outputs.RESOURCE_TARGETS }}
      role_name: GithubActionsRole-Write
      terraform_version: =1.7.0
      tf_backend_name: ${{ vars.TF_BACKEND_PREFIX }}-${{ matrix.environment[0] }}
      tf_backend_key: ${{ github.event.repository.name }}/${{ matrix.stack_name }}
      tfvars_path: ./environments/${{ matrix.environment[0] }}.tfvars
      working_directory: infra/tf/stacks/${{ matrix.stack_name }}
