name: Feature Stack Cleanup

on:
  workflow_dispatch:
    inputs:
      feature_tag:
        description: What is the feature tag? (i.e. abc123)
        required: true
        type: string

  delete:
    # This runs on deletion of branches & tags. If a tag is deleted,
    # the workflow will run, but all jobs after env-vars will be skipped.
    # Github has a fix for this in their backlog to allow you to trigger
    # the workflow only on branch deletion, but it is not yet available.
    # https://github.com/community/community/discussions/10589

permissions:
  contents: read
  id-token: write

env:
  CONTINUE: true
  TF_VERSION: =1.7.0


jobs:
  env-vars:
    name: Set Env Vars as Outputs
    runs-on: ubuntu-latest
    outputs:
      CONTINUE: ${{ steps.set-outputs.outputs.continue }}
      FEATURE_TAG: ${{ steps.set-outputs.outputs.feature_tag }}
      TF_VERSION: ${{ steps.set-outputs.outputs.tf_version }}
    steps:
      # this sets environment variable outputs consumed by downstream jobs
      # this is needed because the 'env' context is not available to reusable workflows
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Output Values
        id: set-outputs
        run: |

          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            # get feature tag from input value
            FEATURE_TAG="${{ github.event.inputs.feature_tag }}"
          else
            # get feature tag from branch name workflow is running against
            FEATURE_TAG="$(./ci-scripts/create-feature-tag.sh ${{ github.event.ref }})"

            # set CONTINUE to false if not a branch deletion
            if [[ "${{ github.event.ref_type }}" == "tag" ]]; then
              CONTINUE=false
              echo "Trigger was a git tag deletion."
              echo "SKIPPING SUBSEQUENT JOBS."
            fi
          fi

          # set continue flag
          echo "continue=${CONTINUE}" >> $GITHUB_OUTPUT

          # set feature tag
          echo "feature_tag=${FEATURE_TAG}" >> $GITHUB_OUTPUT

          # set terraform version
          echo "tf_version=${TF_VERSION}" >> $GITHUB_OUTPUT


  tf-destroy:
    name: Terraform Destroy
    needs: 
      - env-vars
    # using the matrix strategy here because the 'env' context is not available
    # this gives us the ability to define the stack name once and use many times in the inputs
    strategy:
      fail-fast: false
      matrix:
        stack_name:
          - api
    if: ${{ needs.env-vars.outputs.CONTINUE == 'true' }}
    uses: chrisba11/terraform-feature-stacks/.github/workflows/__tf_destroy.yml@main
    with:
      aws_account_id: ${{ vars.DEV_ACCOUNT_ID }}
      aws_region: ${{ vars.AWS_REGION }}
      environment: dev
      feature_tag: ${{ needs.env-vars.outputs.FEATURE_TAG }}
      role_name: GithubActionsRole-Write
      terraform_version: ${{ needs.env-vars.outputs.TF_VERSION }}
      tf_backend_name: ${{ vars.TF_BACKEND_PREFIX }}-dev
      tf_backend_key: ${{ github.event.repository.name }}/feature/${{ matrix.stack_name }}_${{ needs.env-vars.outputs.FEATURE_TAG }}
      tfvars_path: ./environments/dev.tfvars
      working_directory: infra/tf/stacks/${{ matrix.stack_name }}


  delete-feature-git-tag:
    name: Delete Feature Git Tag
    runs-on: ubuntu-latest
    needs:
      - env-vars
      - tf-destroy
    permissions:
      contents: write
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Delete Feature Git Tag
        run: git push --delete origin ${{ needs.env-vars.outputs.FEATURE_TAG }}
