name: Terraform Plan

run-name: Terraform Plan

on:
  workflow_dispatch:

  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'
      - './docs/**'

permissions:
  contents: read
  id-token: write


jobs:
  tf-plan:
    name: Terraform Plan
    strategy:
      fail-fast: false
      matrix:
        STACK_NAME:
          - api
          - oidc
          - storage
        ENVIRONMENT:
          - [dev, '${{ vars.DEV_ACCOUNT_ID }}']
          # - [test, '${{ vars.TEST_ACCOUNT_ID }}']
          # - [prod, '${{ vars.PROD_ACCOUNT_ID }}']
    uses: chrisba11/terraform-feature-stacks/.github/workflows/__tf_plan.yml@v1
    with:
      aws_account_id: ${{ matrix.ENVIRONMENT[1] }}
      aws_region: ${{ vars.AWS_REGION }}
      environment: ${{ matrix.ENVIRONMENT[0] }}
      role_name: GithubActionsRole-ReadOnly
      stack_name: ${{ matrix.STACK_NAME }}
      terraform_version: =1.7.0
      tf_backend_name: ${{ vars.TF_BACKEND_PREFIX }}-${{ matrix.ENVIRONMENT[0] }}
      tf_backend_key: ${{ github.event.repository.name }}/${{ matrix.STACK_NAME }}.tfstate
      tfvars_path: ./environments/${{ matrix.ENVIRONMENT[0] }}.tfvars
      working_directory: infra/tf/stacks/${{ matrix.STACK_NAME }}
